services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - my_media:/vol/web/media
    command:
      sh -c "python manage.py wait_for_db && \
      python manage.py migrate && \
      python manage.py loaddata fixture.json && \
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:17-alpine3.20
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:$PGDATA

volumes:
  my_db:
  my_media:
