# Generated by Django 5.1.2 on 2024-10-17 08:50

import django.db.models.deletion
import django.db.models.functions.text
import planetarium_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium_api", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="astronomyshow",
            options={
                "default_related_name": "astronomy_shows",
                "ordering": (django.db.models.functions.text.Lower("title"),),
            },
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "default_related_name": "reservations",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AlterModelOptions(
            name="showsession",
            options={
                "default_related_name": "show_sessions",
                "ordering": ("-show_time",),
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"default_related_name": "tickets", "ordering": ("row", "seat")},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="astronomyshow",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=planetarium_api.models.astronomy_show_image_file_path,
            ),
        ),
        migrations.AlterField(
            model_name="astronomyshow",
            name="themes",
            field=models.ManyToManyField(to="planetarium_api.showtheme"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="planetarium_api.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="show_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="planetarium_api.showsession",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("show_session", "row", "seat"),
                name="unique_show_session_row_seat",
            ),
        ),
    ]
